### ISSUE TITLE
Remove deprecated sshd options since OpenSSH 7.4

### ISSUE THREAD

**Issue by ellguth** [T-Systems-MMS/puppet-secc_sshd#10]
There are a few deprecated sshd (since openssh 7.4) options in the sshd_config template.
RSAAuthentication, RhostsRSAAuthentication, KeyRegenerationInterval, ServerKeyBits

These options garbage the syslog:
sshd[...]: rexec line 96: Deprecated option RSAAuthentication
sshd[...]: rexec line 104: Deprecated option RhostsRSAAuthentication
sshd[...]: rexec line 138: Deprecated option KeyRegenerationInterval
sshd[...]: rexec line 139: Deprecated option ServerKeyBits

Could you fix this?

**Comment by rkno82** [comment]
Hi Andre, 

we'll do this as soon as we have time for that.
Can you please submit a PR for that?


Thanks,
Robert

**Comment by neubi4** [comment]
Fixed with #11

**Comment by schurzi** [comment]
released version 3.0.0 contains this fix
