### ISSUE TITLE
Implement SoC-Requirements

### ISSUE THREAD

**Issue by pebabape** [T-Systems-MMS/puppet-secc_sshd#16]
**SoC List Secure Shell, latest Version**

**Anforderung 2**: SSH Moduli kleiner als 2048 dürfen nicht genutzt werden - _please remove ssh moduli <2048 from /etc/ssh/moduli_

**Anforderung 3**:  Nur freigegebene Algorithmen zum Schlüsselaustausch dürfen verwendet werden.  - _please remove diffie-hellman-group14-sha1_

- `$ext_sshd_KexAlgorithms                   = 'diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1', `

**Anforderung 7** SSH LoginGraceTime muss auf eine Minute oder niedriger konfiguriert werden. - _please set LoginGraceTime to 
60s (current value 2min/120s)_

**Anforderung 8** SSH MaxAuthTries muss auf 5 oder niedriger gesetzt werden. - _please set MaxAuthTries to 5 (current Value 6)_

**Comment by neubi4** [comment]
In #17 are the changes for requirement 3, 7 and 8.

I have no idea how to fulfill requierement 2, since puppet file_line can not remove lines with an regex. At least Centos 7 does not come with moduli < 2048.

**Comment by schurzi** [comment]
Thank you @neubi4 !
I got some Ideas on how to solve Req2

**Comment by schurzi** [comment]
All Issues are fixed now, fixed release will be 3.2.0
